CREATE SCHEMA `pixomaticcrp` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;

CREATE TABLE IF NOT EXISTS `COMPANIES` (`ID` BIGINT(11) NOT NULL auto_increment , `NAME` VARCHAR(45) NOT NULL, `CIF` VARCHAR(9) NOT NULL UNIQUE, `SHORTDESC` VARCHAR(100), `DESCRIPTION` VARCHAR(255) NOT NULL, `EMAIL` VARCHAR(45) NOT NULL UNIQUE, `CCC` INTEGER(8), `DATE` TINYINT(1), `LOGO` VARCHAR(255) NOT NULL, `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `UPDATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`ID`)) ENGINE=InnoDB;

